// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd9WVXX64PPQUW3ygufSPjDlZdGcFFJgw',
    appId: '1:742127630159:web:be1c1169eb8866e635f73a',
    messagingSenderId: '742127630159',
    projectId: 'pbd--projects-app',
    authDomain: 'pbd--projects-app.firebaseapp.com',
    storageBucket: 'pbd--projects-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd9WVXX64PPQUW3ygufSPjDlZdGcFFJgw',
    appId: '1:742127630159:android:be1c1169eb8866e635f73a',
    messagingSenderId: '742127630159',
    projectId: 'pbd--projects-app',
    storageBucket: 'pbd--projects-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMNcDllhsrmIyqcXpevUlmFE_fRjI5SM0',
    appId: '1:742127630159:ios:322a05e617e6097535f73a',
    messagingSenderId: '742127630159',
    projectId: 'pbd--projects-app',
    storageBucket: 'pbd--projects-app.firebasestorage.app',
    iosBundleId: 'com.example.pbdSolarWindProjects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMNcDllhsrmIyqcXpevUlmFE_fRjI5SM0',
    appId: '1:742127630159:ios:322a05e617e6097535f73a',
    messagingSenderId: '742127630159',
    projectId: 'pbd--projects-app',
    storageBucket: 'pbd--projects-app.firebasestorage.app',
    iosBundleId: 'com.example.pbdSolarWindProjects',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAd9WVXX64PPQUW3ygufSPjDlZdGcFFJgw',
    appId: '1:742127630159:web:be1c1169eb8866e635f73a',
    messagingSenderId: '742127630159',
    projectId: 'pbd--projects-app',
    authDomain: 'pbd--projects-app.firebaseapp.com',
    storageBucket: 'pbd--projects-app.firebasestorage.app',
  );
}